# Build Angular app
FROM node:18 AS build

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build --prod

# Serve using nginx
FROM nginx:alpine
COPY --from=build /app/dist/frontend /usr/share/nginx/html

EXPOSE 80
